#!/bin/bash

# Copy a local (plugin or theme) WordPress project files to a locally hosted WordPress directory
# Should only copy the files required for WordPress to run the plugin or theme and not all possible files
# Copies /local-project-dir and non-excluded files to localhost.domain/wp-content/plugins|themes

# Add copy.sh & copy-config.sh in project root directory
# Configure copy-config.sh
# chmod 755 copy.sh copy-config.sh
# To run, type: ./copy.sh

# DO NOT EDIT THIS FILE

# Config Source.
source $(pwd)/copy-config.sh

WORDPRESS_PROJECT_PATH="${CONFIG_HOST_PATH}/wp-content/${CONFIG_PROJECT_TYPE}/"

DEFAULT_RSYNC_SETTINGS=(
	"--exclude ${CONFIG_PROJECT_SLUG}.zip"
	"--exclude .git"
	"--exclude .gitignore"
	"--exclude .gitattributes"
	"--exclude copy.sh"
	"--exclude copy-config.sh"
	"--exclude README.md"
	"--exclude gulpfile.js"
	"--exclude updates.json"
	"--exclude package.json"
	"--exclude package-lock.json"
	"--exclude node_modules"
)

ITEMS=("${DEFAULT_RSYNC_SETTINGS[@]}" "${CONFIG_RSYNC_SETTINGS[@]}")

clear
printf "\nMoving: $CONFIG_PROJECT_SLUG\n"
printf "Source: $(pwd)\n"
printf "Remote: ${WORDPRESS_PROJECT_PATH}\n\n"

rsync -av --progress --quiet $(pwd) ${WORDPRESS_PROJECT_PATH} $( IFS=$'\n'; echo "${ITEMS[*]}" )


##
## Example copy-config.sh
## Code commented out with ###
##

# Set Project Type: plugins or themes
###CONFIG_PROJECT_TYPE="plugins"

# Set Local Project Directory Slug
###CONFIG_PROJECT_SLUG="my-plugin-name"

# Set Path To Local Project Directory
###CONFIG_PROJECT_PATH="${HOME}/Projects"

# Set Local Host Domain Path
###CONFIG_HOST_PATH="/var/www/html/domain.localhost"

# Set Custom Rsync Settings
###CONFIG_RSYNC_SETTINGS=(
###	"--exclude assets/css/bootstrap4"
###	"--exclude assets/css/style.scss"
###	"--exclude assets/css/_custom-styling.scss"
###	"--exclude assets/css/_custom-variables.scss"
###	"--exclude assets/source"
###	"--exclude assets/psds"
###	"--exclude images/screenshots"
###)
